openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:1323
paths:
  /ping:
    get:
      operationId: Ping_Get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PingResponse"
  /chat/stream:
    get:
      operationId: Chat_Stream_Get
      responses:
        '200':
          description: OK
components:
  schemas:
    PingResponse:
      type: object
      properties:
        message:
          type: string
